project:
  type: website
  output-dir: docs

website:
  title: "Robert Mullins"
  favicon: "favicon-32x32.png"
  navbar:
    title: false
    logo: "logo.png"
    right:
      - href: about.qmd
        text: About
        icon: people
      - href: projects/index.qmd
        text: Projects
        icon: folder
    left:
      - href: index.qmd
        text: Home
        icon: house

format:
  html:
    theme:  
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    css: styles.css
    toc: true
    mainfont: Montserrat  
