project:
  type: website
  output-dir: docs

website:
  title: "Robert Mullins"
  favicon: "favicon-32x32.png"
  navbar:
    title: false
    logo: "logo.png"
    right:
      - href: about.qmd
        text: About
        icon: people
      - href: projects/index.qmd
        text: Projects
        icon: folder
      - text: "CV"
        href: "cv.pdf"        
        icon: file-text
        target: _blank       
      - icon: linkedin
        href: https://www.linkedin.com/in/robert-mullins-176006319/
        aria-label: LinkedIn
        target: _blank
    left:
      - href: index.qmd
        text: Home
        icon: house
    tools:
      - icon: github
        href: https://github.com/robert-mullins
  page-footer:
    left: "Copyright 2026, Robert Mullins"
    right:
      - icon: github
        href: https://github.com/robert-mullins
format:
  html:
    theme:  
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    css: styles.css
    toc: true
    mainfont: Montserrat  
