---
title: "Reflection"
---

## {{< fa book-open >}} My Learning Journey

::: {.callout-note}
This module pushed me to develop both technical and analytical skills I had no prior experience with,
particularly in version control and web development.
:::

---

## {{< fa code >}} Skills Developed

Throughout this module I worked across a range of tools and technologies:

| Skill | Tool | Application |
|---|---|---|
| Version Control | Git & GitHub | Managed all project changes carefully |
| Web Publishing | Quarto & GitHub Pages | Built this portfolio |
| Styling | SCSS & Bootswatch | Customised site theme and layout |

---

## {{< fa list-check >}} Module Checklist

A short checklist which demonstrates how this website has met the main requirements of this assessment:

- [x] Set up a Git repository and commit regularly
- [x] Deploy a Quarto website to GitHub Pages
- [x] Create all required pages (e.g About, Projects, Reflection)
- [x] Add a CV as a linked PDF 
- [x] Create a projects listing with executable Python code
- [x] Customise the theme with SCSS
- [x] Implement a satisfactory number of markdown features
- [x] Implement Google Font 
- [x] Maintain a clean, professional folder repository
- [x] Add all required social links

---

## {{< fa brain >}} Critical Reflection 

### What I Found Challenging 

To be honest, initially the entire assignment felt challenging. I was not very familiar with GitHub, and found it a little intimidating to be constantly pushing things not knowing what might happen. Of course, this was before I learned about rendering and previews. There were initially a number of occassions where I had to start from scratch, but each time I progressed further. Initially, implementing active Python code was also quite difficult, but I was able to overcome this over time.

### What I Would Do Differently 

If I was to start again, I would aim to have a more established plan and list of tasks that need to be done. Whilst the final assignment rubric helped a lot of formulating a plan, I should’ve had one set up myself beforehand as it would’ve prevented chaotic additions and then retractions to my portfolio.

### How These Skills Apply Beyond This Module 

The combination of Git, Python, and web publishing is directly transferable to data analyst and business intelligence roles. Being able to present analysis in a professional self-made portfolio, and to be familiar with GitHub is a necessary skill nowadays. An underrated part of this assignment is that it has also given us a GitHub commit history, which can be checked by some employers (particularly if I was to go into data analytics). I also became far more comfortable with using VS Code, software that is nowadays synonymous with programming. Although I mostly aim to further my education and perhaps pursue academia, the skills I have learned from this project will allow me to easily differentiate myself.

## {{< fa arrow-right >}} Future Goals 
 
 I plan to keep using this portfolio after graduating to differentiate myself in a tight job market, whilst adding to it as I plan my own projects outside of university. I aim to implement data analytics to whatever industry I enter, as I am a firm believer that having more information at your disposal is always beneficial, no matter the setting. I am genuinely grateful to have had the experience to complete this assessment, and believe it will serve me well in the future.
